[project]
name = "anyrule"
version = "0.1.0"
description = "Declarative rule engine"
authors = [
    {name = "Ivan Georgiev",email = "ivan.georgiev@nl.abnamro.com"}
]
license = {text = "GPL"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "parse (>=1.20.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
  "--cov=src",
  "--cov-config=pyproject.toml",
  "--cov-report=xml",
  "--cov-report=term-missing",
  "--cov-report=html",
  "--cov-fail-under=60",
  "--junitxml=junit.xml"
]
minversion = "6.0"
testpaths = [
  "tests"
]
pythonpath = [
  "src"
]

[tool.coverage.report]
skip_empty = true
omit = [
       "src/**/*cli*/**",
       "src/*/django_app/**",
       "src/*/fast_api/**",
       "src/*/services/**",
       "src/*/rules/**"
]

[tool.coverage.run]
branch = true
source = ["src"]
relative_files = true

[tool.poetry.scripts]
# hack-dam = "hackathon_dcam.cli:click_cli"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.0.0"
pytest = "^8.3.5"

